# Tensor의 random 선언

In [1]:
import torch
import numpy as np

### [0,1), 0~1사이의 Uniform distribution random 값으로 선언

In [2]:
a1 = torch.rand(3,3) 
print(a1)


 0.4895  0.6493  0.4671
 0.6286  0.3212  0.4192
 0.0319  0.2269  0.4889
[torch.FloatTensor of size 3x3]



### Z(0,1), 평균이 0이고 분산이 1인 Normal distribution random 값으로 선언

In [3]:
b1 = torch.randn(3,3) 
print(b1)


 1.8956 -1.2530 -0.3635
 0.0051 -0.0470 -1.3748
-0.0265  0.4448  1.3507
[torch.FloatTensor of size 3x3]



***

# Numpy -> Tensor, Tensor -> Numpy

### Numpy -> Tensor

In [4]:
a2 = np.array([[1,2,3,4],[5,6,7,8]]) 
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
b2 = torch.Tensor(a2)
print(b2)


 1  2  3  4
 5  6  7  8
[torch.FloatTensor of size 2x4]



### Tensor -> Numpy

In [6]:
a3 = torch.rand(3,3)
print(a3)


 0.0239  0.5365  0.1191
 0.3408  0.3618  0.2630
 0.5905  0.8621  0.8219
[torch.FloatTensor of size 3x3]



In [7]:
b3 = a3.numpy()
print(b3)

[[ 0.02386206  0.53646123  0.11912364]
 [ 0.34078413  0.36176103  0.26300836]
 [ 0.59049612  0.86214596  0.82185543]]


***

# Tensor의 형태변환

In [8]:
a4 = torch.rand(3,3)
print(a4)


 0.0746  0.6314  0.2176
 0.7523  0.5827  0.0072
 0.1738  0.6780  0.4135
[torch.FloatTensor of size 3x3]



In [9]:
b4 = a4.view(1,1,3,3)
print(b4)


(0 ,0 ,.,.) = 
  0.0746  0.6314  0.2176
  0.7523  0.5827  0.0072
  0.1738  0.6780  0.4135
[torch.FloatTensor of size 1x1x3x3]



***

# Tensor 합치기

In [10]:
a5 = torch.randn(1,1,3,3)
b5 = torch.randn(1,1,3,3)
print(a5)
print(b5)


(0 ,0 ,.,.) = 
 -0.4311  0.2055  0.4454
  0.7313  0.1510  0.5992
  0.5800 -0.5691  1.1705
[torch.FloatTensor of size 1x1x3x3]


(0 ,0 ,.,.) = 
  1.1027 -0.0847 -0.5226
  0.0740 -0.5331 -1.0769
  0.6502  1.1770 -0.2568
[torch.FloatTensor of size 1x1x3x3]



### torch.cat((Tensor_A, Tensor_B), dim)

In [11]:
c = torch.cat((a5,b5), 0)
print(c)


(0 ,0 ,.,.) = 
 -0.4311  0.2055  0.4454
  0.7313  0.1510  0.5992
  0.5800 -0.5691  1.1705

(1 ,0 ,.,.) = 
  1.1027 -0.0847 -0.5226
  0.0740 -0.5331 -1.0769
  0.6502  1.1770 -0.2568
[torch.FloatTensor of size 2x1x3x3]



In [12]:
d = torch.cat((a5,b5), 1)
print(d)


(0 ,0 ,.,.) = 
 -0.4311  0.2055  0.4454
  0.7313  0.1510  0.5992
  0.5800 -0.5691  1.1705

(0 ,1 ,.,.) = 
  1.1027 -0.0847 -0.5226
  0.0740 -0.5331 -1.0769
  0.6502  1.1770 -0.2568
[torch.FloatTensor of size 1x2x3x3]



In [13]:
e = torch.cat((a5,b5), 2)
print(e)


(0 ,0 ,.,.) = 
 -0.4311  0.2055  0.4454
  0.7313  0.1510  0.5992
  0.5800 -0.5691  1.1705
  1.1027 -0.0847 -0.5226
  0.0740 -0.5331 -1.0769
  0.6502  1.1770 -0.2568
[torch.FloatTensor of size 1x1x6x3]



In [14]:
f = torch.cat((a5,b5), 3)
print(f)


(0 ,0 ,.,.) = 
 -0.4311  0.2055  0.4454  1.1027 -0.0847 -0.5226
  0.7313  0.1510  0.5992  0.0740 -0.5331 -1.0769
  0.5800 -0.5691  1.1705  0.6502  1.1770 -0.2568
[torch.FloatTensor of size 1x1x3x6]



***

# Tensor 계산을 GPU로

In [15]:
a6 = torch.rand(3,3)
b6 = torch.rand(3,3)

print(a6)
print(b6)


 0.8949  0.5610  0.6727
 0.9176  0.5765  0.7993
 0.3609  0.6836  0.4628
[torch.FloatTensor of size 3x3]


 0.7289  0.3471  0.8449
 0.0891  0.0057  0.3793
 0.9546  0.8606  0.2992
[torch.FloatTensor of size 3x3]



In [16]:
# a6 = a6.cuda()
# b6 = b6.cuda()

sum = a6 + b6
print(sum)


 1.6238  0.9080  1.5176
 1.0067  0.5822  1.1787
 1.3155  1.5442  0.7620
[torch.FloatTensor of size 3x3]



***

# 그 외

In [17]:
a7 = torch.rand(3,3)
print(a7)


 0.2286  0.7413  0.0533
 0.2650  0.7164  0.8704
 0.0463  0.7318  0.2276
[torch.FloatTensor of size 3x3]



In [18]:
b7 = a7.mean()
print(b6)


 0.7289  0.3471  0.8449
 0.0891  0.0057  0.3793
 0.9546  0.8606  0.2992
[torch.FloatTensor of size 3x3]



In [19]:
b7 = a7.sum()
print(b7)

3.880752444267273
